version: "3.7"
services:

  php:
    build:
      context: php-fpm
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html/
      - ./server/000-default.conf:/etc/apache2/sites-available/000-default.conf
  composer:
    image: 'composer:latest'
    volumes:
      - './:/app'
  database:
    image: mariadb:10.4
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mdsproject
      - MYSQL_USER=amine
      - MYSQL_PASSWORD=azerty
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - database
    ports:
      - "8081:80"
    environment:
      PMA_HOST: database